# Generated by Django 4.0 on 2022-01-04 18:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_name', models.CharField(max_length=30)),
                ('stocks', models.IntegerField(default=0)),
                ('on_promo', models.BooleanField(default=False)),
                ('category', models.IntegerField()),
                ('num_reviews', models.IntegerField(default=0)),
                ('review_path', models.CharField(max_length=30)),
                ('num_rating', models.IntegerField(default=0)),
                ('rating_path', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WebUsers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('url', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=30)),
                ('cart_path', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_History',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.items')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.webusers')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.webusers'),
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='[0-9]{16}')])),
                ('cvv', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='[0-9]{3}')])),
                ('expire_month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('expire_day', models.IntegerField(validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('billing_address', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='\\D\\d\\D{2}')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.webusers')),
            ],
            options={
                'unique_together': {('card_id', 'user_id')},
            },
        ),
    ]
