# Generated by Django 4.0 on 2022-01-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase_History',
            new_name='PurchaseHistory',
        ),
        migrations.RenameModel(
            old_name='WebUsers',
            new_name='Users',
        ),
    ]
