# Generated by Django 4.0 on 2022-01-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_items_item_id_alter_items_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='user_name',
        ),
    ]
